export const DASHBOARD_ACTIONS = {
  // ABOUT
  SET_DASHBOARD_ABOUT: "SET_DASHBOARD_ABOUT",
  DELETE_DASHBOARD_ABOUT_ITEM: "DELETE_DASHBOARD_ABOUT_ITEM",
  EDIT_DASHBOARD_ABOUT_ITEM: "EDIT_DASHBOARD_ABOUT_ITEM",
  CREATE_DASHBOARD_ABOUT_ITEM: "CREATE_DASHBOARD_ABOUT_ITEM",

  // LANGUAGE
  SET_DASHBOARD_LANGUAGES: "SET_DASHBOARD_LANGUAGES",
  DELETE_DASHBOARD_LANGUAGE_ITEM: "DELETE_DASHBOARD_LANGUAGE_ITEM",
  EDIT_DASHBOARD_LANGUAGE_ITEM: "EDIT_DASHBOARD_LANGUAGE_ITEM",
  CREATE_DASHBOARD_LANGUAGE_ITEM: "CREATE_DASHBOARD_LANGUAGE_ITEM",

  // SKILLS
  SET_DASHBOARD_SKILLS: "SET_DASHBOARD_SKILLS",
  EDIT_DASHBOARD_SKILL_ITEM: "EDIT_DASHBOARD_SKILL_ITEM",
  CREATE_DASHBOARD_SKILL_ITEM: "CREATE_DASHBOARD_SKILL_ITEM",
  DELETE_DASHBOARD_SKILL_ITEM: "DELETE_DASHBOARD_SKILL_ITEM",
} as const;
