export const SET_DASHBOARD_ABOUT = 'SET_DASHBOARD_ABOUT';
export const SET_DASHBOARD_LANGUAGES = 'SET_DASHBOARD_LANGUAGES';
export const SET_DASHBOARD_PORTFOLIO = 'SET_DASHBOARD_PORTFOLIO';
export const SET_DASHBOARD_SKILLS = 'SET_DASHBOARD_SKILLS';

export const DELETE_DASHBOARD_ABOUT_ITEM = 'DELETE_DASHBOARD_ABOUT_ITEM';
export const EDIT_DASHBOARD_ABOUT_ITEM = 'EDIT_DASHBOARD_ABOUT_ITEM';
export const CREATE_DASHBOARD_ABOUT_ITEM = 'CREATE_DASHBOARD_ABOUT_ITEM';

export const DELETE_DASHBOARD_LANGUAGE_ITEM = 'DELETE_DASHBOARD_LANGUAGE_ITEM';
export const EDIT_DASHBOARD_LANGUAGE_ITEM = 'EDIT_DASHBOARD_LANGUAGE_ITEM';
export const CREATE_DASHBOARD_LANGUAGE_ITEM = 'CREATE_DASHBOARD_LANGUAGE_ITEM';

export const EDIT_DASHBOARD_SKILL_ITEM = 'EDIT_DASHBOARD_SKILL_ITEM';
export const CREATE_DASHBOARD_SKILL_ITEM = 'CREATE_DASHBOARD_SKILL_ITEM';
export const DELETE_DASHBOARD_SKILL_ITEM = 'DELETE_DASHBOARD_SKILL_ITEM';
