export const SET_DASHBOARD_ABOUT = 'SET_DASHBOARD_ABOUT';
export const SET_DASHBOARD_LANGUAGES = 'SET_DASHBOARD_LANGUAGES';
export const SET_DASHBOARD_PORTFOLIO = 'SET_DASHBOARD_PORTFOLIO';
export const SET_DASHBOARD_SKILLS = 'SET_DASHBOARD_SKILLS';
